image: gitpod/workspace-full

tasks:
  - init: |
      cargo install wasm-pack
      npm run build:wasm
      npm run dev
vscode:
  extensions:
    - matklad.rust-analyzer
    - bungcip.better-toml
    - serayuzgur.crates